blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),

]

core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(Status='pub')


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'dr', 'Draft'
        PUBLISHED = 'pub', 'Published'

    title = models.CharField(max_length=600)
    slug = models.SlugField(max_length=200, unique=True, unique_for_date='published')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    Status = models.CharField(max_length=10, choices=Status.choices, default=Status.DRAFT)
    tags = TaggableManager()

    class Meta:
        ordering = ('-published',)
        indexes = [
            models.Index(fields=['-published']),
        ]

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[
            self.published.year,
            self.published.month,
            self.published.day,
            self.slug])

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=25)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms
from .models import Comment
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        required=False,
        widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            'name',
            'email',
            'body',
            Submit('submit', 'Add Comment', css_class='btn btn-primary')
        )

blog/views.py
from django.core.mail import send_mail
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_POST
from taggit.models import Tag

from .forms import EmailPostForm, CommentForm
from .forms import EmailPostForm, CommentForm
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger  # Create your views here.
from django.views.generic import ListView
from django.db.models import Count 


# This is the function based view

def post_list(request, tag_slug=None):
    post_list = Post.objects.filter(Status='pub')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

    paginator = Paginator(post_list, 5)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/list.html', {'posts': posts, 'tag': tag})







"""
class PostListView(ListView, tag_slug=None):
    queryset = Post.objects.filter(Status='pub')
    
    context_object_name = ['posts', 'tag']
    paginate_by = 5
    template_name = 'blog/post/list.html'
    
"""


def post_detail(request, year, month, day, post):
    # try:
    #     post = Post.objects.get(id=id)
    # except Post.DoesNotExist:
    #     raise Http404('Post not found')
    post = get_object_or_404(Post,
                             slug=post,
                             published__year=year,
                             published__month=month,
                             published__day=day,

                             )
    comments = post.comments.filter(active=True)
    form = CommentForm()
    
    
    # List of similler post 
    post_tags_ids = post.tags.values_list('id', flat=True)
    similler_posts = Post.objects.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similler_posts = similler_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-published')[:4]
    
    return render(request,
                  'blog/post/detail.html', {'post': post, 'comments': comments, 'form': form, 'similler_posts': similler_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'admin@myblog', [cd['to']])
            sent = True

    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, )
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
        return render(request, 'blog/post/comment.html', {
            'post': post,
            'form': form,
            'comment': comment})

blog/templates/blog/base.html
{% load blog_tags %}
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{%static 'css/styles.css' %}" rel="stylesheet" />
    <link href="{%static 'css/custom.css' %}" rel="stylesheet" />
    <link href="{%static 'css/bootstrap.min.css' %}" rel="stylesheet" />

    
</head>
<body>

       <!-- Navigation-->
       <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="index.html">Aldinn</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

        <!-- Page Header-->
        <header class="masthead" style="background-image: url('https://i.ibb.co/W69R3DT/home-bg.jpg');  background-repeat: no-repeat;">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">

                        {% if request.path == '/blog/' %}
                        

                        <div class="site-heading">
                            <h1>Aldinn Blog</h1>
                            <span class="subheading">A Blog Theme by Aldinn</span>
                        </div>


                    {% else %}

                    <div class="post-heading">
                        <h1>{%block post_title%}{%endblock%}</h1>
                        {% comment %} <h2 class="subheading"></h2> {% endcomment %}
                        <span class="meta">
                            Posted by
                            <a href="#!">{%block post_author %} {%endblock%}</a>
                            on {% block post_published %}{% endblock post_published %}
                        </span>

                    </div>

                    {% endif %}





                    </div>
                </div>
            </div>
        </header>


    
        <section class="container mx-auto">
            <p>This is my blog</p>
            I have {% Posts_count %} posts
        </section>
    

        {%block content%}
        {%endblock%}
























        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>



        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
        <link href="{%static 'js/styles.css' %}" rel="stylesheet" />

{% comment %} </body>

<a href="https://ibb.co/bJfM00v"><img src="https://i.ibb.co/bJfM00v/about-bg.jpg" alt="about-bg" border="0"></a> 
<a href="https://ibb.co/W0L2rCV"><img src="https://i.ibb.co/W0L2rCV/contact-bg.jpg" alt="contact-bg" border="0"></a> 
<a href="https://ibb.co/7Xc0zg9"><img src="https://i.ibb.co/7Xc0zg9/home-bg.jpg" alt="home-bg" border="0"></a> 
<a href="https://ibb.co/12LL60v"><img src="https://i.ibb.co/12LL60v/post-bg.jpg" alt="post-bg" border="0"></a> 
<a href="https://ibb.co/F6d5cHN"><img src="https://i.ibb.co/F6d5cHN/post-sample-image.jpg" alt="post-sample-image" border="0"></a>

{% endcomment %}

blog/templates/blog/pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
    {% if page.has_previous %}
      <li class="page-item ">
        <a href="?page={{ page.previous_page_number }}" class="page-link">Previous</a>
        
    </li>
    
    {% endif %}
      

      


      <li class="page-item"><a class="page-link" href="#">{{page.number}} {{page.paginator.num_page}}</a></li>
      {% if page.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
      </li>
      {% endif %}
    </ul>
  </nav>

blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}
{% block title %}Add a comment{% endblock %}
{% block content %}
    {% if comment %}
        <div class="container">
            <h2>Your comment has been added.</h2>
            <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
        </div>
    {% else %}

        <div class="container">
            {% include "blog/post/includes/comment_form.html" %}
        </div>
    {% endif %}
{% endblock %}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}


{% block title %}

    {{ post.title }}

{% endblock %}
{% block post_title %}{{ post.title }}{% endblock %}
{% block post_published %}{{ post.published }}{% endblock %}
{% block post_author %}{{ post.author }}{% endblock %}

{% block content %}








    <article class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {{ post.body|linebreaks }}
                </div>
            </div>
        </div>
    </article>
   
    <div class="container">

    <p>
        <a href="{% url "blog:post_share"  post.id %}">
            Share This Post
        </a>
    </p>


    <h2>Similar Posts</h2>

    {% for post in similler_posts %}
        <h3>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h3>
        {% empty %}
        <p>
            {{ post.body|truncatewords:30|linebreaks }}
        </p>

    {% endfor %}


    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}

    {% for comments in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comments.name }}
                {{ comments.created }}
            </p>
            {{ comments.body|linebreaks }}
        </div>

    {% endfor %}

    {% include "blog/post/includes/comment_form.html" %}

</div>
{% endblock %}

blog/templates/blog/post/includes/comment_form.html
{% load crispy_forms_tags %}
<h2>
    Add New Comment
</h2>

<form action="{% url "blog:post_comment" post.id %}" method="post">
    {% csrf_token %}
    {% crispy form %}
</form>

blog/templates/blog/post/list.html
{% extends "blog/base.html"%}


{% block title %} My Blog {%endblock%}


{% block content%}



<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">

        {% comment %} {% if tag %}
            <h1>Posts tagged with "{{ tag.name }}"</h1>
        {% endif %} {% endcomment %}

            {% for post in posts %}
            <!-- Post preview-->
            <div class="post-preview">
                <a href="{{ post.get_absolute_url }}">
                    <h2 class="post-title">{{post.title}}</h2>
                    
                    {% for tag in post.tags.all %}
                        <a href="{% url "blog:post_list_by_tag" tag.slug %}">

                        {{ tag.name }}


                        </a>

                        {% if not forloop.last %}, {% endif %}


                    {% endfor %}
                    
                    
                    
                    <h3 class="post-subtitle">{{post.body|truncatewords:30|linebreaks }}</h3>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#!">{{post.author}}</a>
                    {{post.published}}
                    <span>tags:</span>
                    <a>{{ post.tags.all | join:"," }}</a>

                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />

            {% endfor %}
            <!-- Pager-->
            {% include "blog/pagination.html" with page=page_obj %}

        </div>
    </div>
</div>

{% include 'blog/pagination.html' with page=posts %}


{% endblock%}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}

        Share Post


{% endblock %}

{% block content %}
{% if sent %}
    <h1>Thank you for sharing this post</h1>
    <p>"{{ post.title }} was successfully sent to {{ form.cleaned_data.to }}" </p>
{% else %}
    <h1>Share Post {{ post.title }}</h1>
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Send Me  Mail">
    </form>
{% endif %}
{% endblock %}